resolver: lts-3.0
flags: {}
packages:
- .
- location:
    git: file:///Users/sseefried/code/forked-git/helm
    commit: 01d207616fb0e9c098a47590600a7751d4db5062
- location:
    git: file:///Users/sseefried/code/forked-git/hsSDL2

    commit: 3310dc870d840d18e81153fccc71dab4ed97f932
- location:
    git: https://github.com/sseefried/hs-cairo
    commit: 922c6fab2d632c220ebd3f07b737e75537bfda70

extra-deps:
 - elerea-2.8.0
 - utf8-string-0.3.8
 - pango-0.13.1.0
 - glib-0.13.1.0


